import os
import time
import numpy as np

def construct_mesh(arr: np.ndarray, out_path):
    if not isinstance(arr, np.ndarray):
        raise TypeError("arr must be a numpy array")
    if arr.ndim != 3:
        raise ValueError(f"arr must be 3D (Z,Y,X). Got shape {arr.shape}")
    if arr.size == 0:
        raise ValueError("arr is empty")

    vol = arr.astype(np.float32)
    if np.max(vol) <= 0:
        raise ValueError("Mask is empty (all zeros). No mesh to build.")

    from skimage.measure import marching_cubes

    verts, faces, normals, values = marching_cubes(vol, level=0.5)

    # --- NEW: center mesh on barycenter ---
    barycenter = verts.mean(axis=0)
    verts = verts - barycenter
    # --------------------------------------

    output_folder = "/home/jovyan/work/output"
    os.makedirs(output_folder, exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# OBJ generated by marching cubes\n")
        for v in verts:
            z, y, x = v
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for tri in faces:
            i, j, k = tri
            f.write(f"f {i+1} {j+1} {k+1}\n")

    print(f"[OK] Mesh saved to: {out_path}")
    return out_path